variable "name" {
  type        = string
  description = "(Required) The name of the provider to create."
}

variable "saml_metadata_document" {
  type        = string
  description = "(Required) An XML document generated by an identity provider that supports SAML 2.0."
}
