variable "certificate" {
  description = "The Amazon Resource Name (ARN) of the AWS Certificate Manager (ACM) certificate. This is required when protocols is set to FTPS."
  type        = string
}

variable "domain" {
  description = "The domain of the storage system that is used for file transfers. Valid values are: S3 and EFS."
  type        = string
  default     = "S3"
}

variable "protocols" {
  description = "Specifies the file transfer protocol or protocols over which your file transfer protocol client can connect to your server's endpoint. The available protocols are AS2, SFTP, FTPS, and FTP."
  type        = list(string)
  default     = ["SFTP"]
}

variable "endpoint_type" {
  description = "The type of endpoint that you want your SFTP server connect to. If you connect to a VPC (or VPC_ENDPOINT), your SFTP server isn't accessible over the public internet. If you want to connect your SFTP server via public internet, set PUBLIC."
  type        = string
  default     = "PUBLIC"
}

variable "invocation_role" {
  description = "Amazon Resource Name (ARN) of the IAM role used to authenticate the user account with an identity_provider_type of API_GATEWAY."
  type        = string
}

variable "host_key" {
  description = "RSA, ECDSA, or ED25519 private key (e.g., as generated by the ssh-keygen command)."
  type        = string
}

variable "url" {
  description = "URL of the service endpoint used to authenticate users with an identity_provider_type of API_GATEWAY."
  type        = string
}

variable "identity_provider_type" {
  description = "The mode of authentication enabled for this service. Options are SERVICE_MANAGED, API_GATEWAY, AWS_DIRECTORY_SERVICE, and AWS_LAMBDA."
  type        = string
  default     = "SERVICE_MANAGED"
}

variable "directory_id" {
  description = "The directory service ID of the directory service you want to connect to with an identity_provider_type of AWS_DIRECTORY_SERVICE."
  type        = string
}

variable "function" {
  description = "The ARN for a lambda function to use for the Identity provider."
  type        = string
}

variable "logging_role" {
  description = "Amazon Resource Name (ARN) of an IAM role that allows the service to write your SFTP users’ activity to your Amazon CloudWatch logs for monitoring and auditing purposes."
  type        = string
}

variable "force_destroy" {
  description = "A boolean that indicates all users associated with the server should be deleted so that the Server can be destroyed without error. This option only applies to servers configured with a SERVICE_MANAGED identity_provider_type."
  type        = bool
  default     = false
}

variable "post_authentication_login_banner" {
  description = "Specify a string to display when users connect to a server. This string is displayed after the user authenticates."
  type        = string
}

variable "pre_authentication_login_banner" {
  description = "Specify a string to display when users connect to a server. This string is displayed before the user authenticates."
  type        = string
}

variable "security_policy_name" {
  description = "Specifies the name of the security policy that is attached to the server. Possible values are TransferSecurityPolicy-2018-11, TransferSecurityPolicy-2020-06, TransferSecurityPolicy-FIPS-2020-06, TransferSecurityPolicy-2022-03, and TransferSecurityPolicy-2023-05."
  type        = string
}

variable "structured_log_destinations" {
  description = "A set of ARNs of destinations that will receive structured logs from the transfer server such as CloudWatch Log Group ARNs."
  type        = list(string)
}

variable "tags" {
  description = "A map of tags to assign to the resource."
  type        = map(string)
}

variable "address_allocation_ids" {
  description = "A list of address allocation IDs that are required to attach an Elastic IP address to your SFTP server's endpoint."
  type        = list(string)
}

variable "security_group_ids" {
  description = "A list of security groups IDs that are available to attach to your server's endpoint."
  type        = list(string)
}

variable "subnet_ids" {
  description = "A list of subnet IDs that are required to host your SFTP server endpoint in your VPC."
  type        = list(string)
}

variable "vpc_endpoint_id" {
  description = "The ID of the VPC endpoint. This property can only be used when endpoint_type is set to VPC_ENDPOINT."
  type        = string
}

variable "vpc_id" {
  description = "The VPC ID of the virtual private cloud in which the SFTP server's endpoint will be hosted."
  type        = string
}

variable "as2_transports" {
  description = "Indicates the transport method for the AS2 messages. Currently, only HTTP is supported."
  type        = list(string)
}

variable "passive_ip" {
  description = "Indicates passive mode, for FTP and FTPS protocols. Enter a single IPv4 address, such as the public IP address of a firewall, router, or load balancer."
  type        = string
}

variable "set_stat_option" {
  description = "Use to ignore the error that is generated when the client attempts to use SETSTAT on a file you are uploading to an S3 bucket. Valid values: DEFAULT, ENABLE_NO_OP."
  type        = string
}

variable "tls_session_resumption_mode" {
  description = "Provides a mechanism to resume or share a negotiated secret key between the control and data connection for an FTPS session. Valid values: DISABLED, ENABLED, ENFORCED."
  type        = string
}

variable "workflow_execution_role" {
  description = "Includes the necessary permissions for S3, EFS, and Lambda operations that Transfer can assume, so that all workflow steps can operate on the required resources."
  type        = string
}

variable "workflow_id" {
  description = "A unique identifier for the workflow."
  type        = string
}

variable "workflow_detail" {
  description = "A map containing the execution_role and workflow_id for triggering workflows on upload and partial upload events."
  type = object({
    execution_role = string
    workflow_id    = string
  })
}
