variable "display_name" {
  type        = string
  description = "(Optional) The display name for the SNS topic"
}

variable "name" {
  type        = string
  description = "(Optional) The friendly name for the SNS topic. By default generated by Terraform."
}

