---
name: Build
on:
  pull_request:
    branches:
      - main

jobs:
  build_terraform:
    name: Build - Terraform
    runs-on: ubuntu-latest

    steps:
      - name: HashiCorp - Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.ref }}

      - name: Terraform fmt on all files
        id: fmt
        run: terraform fmt -recursive

      - name: Build terraform docs
        uses: terraform-docs/gh-actions@main
        with:
          config-file: ./modules/.terraform-docs.yml
          find-dir: ./modules

      - name: Git stage all, commit, and push
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Continuous Integration - terraform fmt and terraform-docs